### ISSUE TITLE
Reentrant Parser (for Multithreaded Parsing without side-effects)

### ISSUE THREAD

**Issue by da-h** [lukeparser/pybison#11]
Adding `%option reentrant` results in same errors as in this thread:
https://stackoverflow.com/questions/2634998/writing-re-entrant-lexer-with-flex

However, it would be nice to make the parser thread-safe.

**Comment by sbrodehl** [comment]
Interesting!

**Comment by sbrodehl** [comment]
What needs to be done besides 5ded6f5ffc9a9037878dda5cbd4ed14eef68b50f?

**Comment by da-h** [comment]
Indeed, it IS done!
