### ISSUE TITLE
distutils is deprecated planned for Python 3.12

### ISSUE THREAD

**Issue by da-h** [lukeparser/pybison#34]
From the docs:
> [distutils](https://docs.python.org/3/library/distutils.html#module-distutils) is deprecated with removal planned for Python 3.12. See the [What’s New](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated) entry for more information.

The use of `distutils` should therefore be replaced in the near future, especially from `.buildLib()` (in `bison_.pyx`), which is probably a bit outdated anyway.

**Comment by sbrodehl** [comment]
Thanks for bringing this up!
I can take care of this if you like?

**Comment by da-h** [comment]
Sure, this would be great! :+1:
